---

sudo: required

language: python

python: 2.7

services:
  - docker

env:
  - OS_VERSION=6.5

before_install:
  - sudo docker pull hasedon/centos${OS_VERSION}
  - sudo docker run --detach --volume="${PWD}":/root/django_deployment:ro --name centos-${OS_VERSION} hasedon/centos${OS_VERSION} sleep 300
  - sudo docker exec centos-${OS_VERSION} yum -y install tar bzip2 unzip gcc 
  - sudo docker exec centos-${OS_VERSION} wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O /tmp/miniconda.sh
  - sudo docker exec centos-${OS_VERSION} chmod +x /tmp/miniconda.sh
  - sudo docker exec centos-${OS_VERSION} ./tmp/miniconda.sh -b -p /home/travis/miniconda2
  # - sudo docker exec centos-${OS_VERSION} export PATH=/home/travis/miniconda2/bin:$PATH
  # - echo $PATH
  - sudo docker exec centos-${OS_VERSION} /home/travis/miniconda2/bin/conda update --yes conda

install:
  - sudo docker exec centos-${OS_VERSION} yum -y install epel-release
  - sudo docker exec centos-${OS_VERSION} /home/travis/miniconda2/bin/conda install --yes -c bioconda ansible
    # - pip install -i https://pypi.anaconda.org/pypi/simple yum    

script:
  - echo localhost > hosts
  - sudo docker exec centos-${OS_VERSION} ls -al /root/django_deployment
  - sudo docker exec centos-${OS_VERSION} /home/travis/miniconda2/bin/ansible-playbook -i hosts -vvv /root/django_deployment/django_app_server_db_server/deployment/main.yml --connection=local --check

