---
  
- name: Install OS Dependencies (Debian)
  package: name={{ item }} state=present
  with_items:
    - sudo
    - build-essential
    - libpq-dev
    - postgresql-client
    - postgresql-client-common
    - uwsgi
    - uwsgi-plugin-python

- name: Setup miniconda path (Debian)
  lineinfile: dest=/root/.{{ item }} regexp="miniconda2" line="PATH=/opt/miniconda2/bin:$PATH"
  with_items:
    - bashrc
    - profile

- name: Add root as temporary sudoers
  lineinfile: "dest=/etc/sudoers regexp='^root' line='root ALL=(ALL)       NOPASSWD: ALL' state=present"

- name: Install uwsgi.ini file
  template: src=templates/uwsgi_ubuntu.ini dest=/etc/uwsgi/apps-available/eclaim.ini mode=0644

- name: Symlink eclaim.ini file
  file: src=/etc/uwsgi/apps-available/eclaim.ini dest=/etc/uwsgi/apps-enabled/eclaim.ini state=link
  notify: restart uwsgi
