- name: Chmod manage.py
  file: path={{ django_app_home }}/manage.py state=file mode=0775

- name: Run eclaim migrate
  django_manage: command="migrate auth --noinput" app_path={{ django_app_home }} virtualenv=/opt/miniconda2

- name: Run eclaim migrate
  django_manage: command="migrate --noinput" app_path={{ django_app_home }} virtualenv=/opt/miniconda2

- name: Run eclaim collectstatic
  django_manage: command=collectstatic app_path={{ django_app_home }} virtualenv=/opt/miniconda2
