- name: Chmod manage.py
  file: path=/opt/eclaim_revamp/eclaim/manage.py state=file mode=0775
  when: app_version == "eclaim_revamp"

- name: Run eclaim migrate
  django_manage: command="migrate auth --noinput" app_path=/opt/eclaim_revamp/eclaim virtualenv=/opt/miniconda2
  when: app_version == "eclaim_revamp"

- name: Run eclaim migrate
  django_manage: command="migrate --noinput" app_path=/opt/eclaim_revamp/eclaim virtualenv=/opt/miniconda2
  when: app_version == "eclaim_revamp"

- name: Run eclaim collectstatic
  django_manage: command=collectstatic app_path=/opt/eclaim_revamp/eclaim virtualenv=/opt/miniconda2
  when: app_version == "eclaim_revamp"
