---

- name: Install OS & App Dependencies specific for eclaim
  package: name={{ item }} state=present
  with_items:
    - mercurial

- name: Edit uwsgi.ini file for eclaim
  lineinfile:
    dest: /etc/uwsgi.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
    state: present
  with_items:
    - { regexp: 'wsgi-file=/opt/eclaim/eclaim/wsgi.py', line: 'wsgi-file=/opt/eclaim/eclaim/eclaim.wsgi' }
    - { regexp: 'harakiri=20', line: '#harakiri=20' }

- name: Edit uwsgi file for eclaim
  lineinfile:
    dest: /etc/rc.d/init.d/uwsgi
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
    state: present
  with_items:
    - { regexp: 'PATH=/sbin:/bin:/usr/sbin:/usr/bin', line: 'PATH=/opt/miniconda2/bin:/sbin:/bin:/usr/sbin:/usr/bin' }
    - { regexp: 'PROG=/opt/miniconda2/bin/uwsgi', line: 'PROG=uwsgi' }

- name: Rub out old eclaim folder
  file: path=/opt/eclaim state=absent

- name: Make sure pillow installed for eclaim
  # conda: name=pillow state=latest executable=/opt/miniconda2/bin/conda
  shell: /opt/miniconda2/bin/conda list | grep -q -i pillow || /opt/miniconda2/bin/conda install --yes -c ryan pillow
  args:
    creates: /opt/miniconda2/lib/python2.7/site-packages/PIL

- name: Checkout eclaim source code
  hg: repo={{ deployment_url }} dest=/opt/eclaim force=yes version=default

- name: Downgrade pip to 6.1.1
  shell: pip install pip==6.1.1

- name: Setup pip requirements for eclaim
  pip: requirements=/opt/eclaim/eclaim/requirements.txt virtualenv=/opt/miniconda2
