---

- name: Install OS Dependencies
  yum: name={{ item }} state=present
  with_items:
    - git
    - unzip
    - tar
    - bzip2
    - postgresql-devel
    - gcc
    - glibc-common
    - nginx

- name: Rub out old eclaim_revamp folder
  file: path=/opt/eclaim_revamp state=absent

- include: install_conda.yml

- name: Setup miniconda path
  lineinfile: dest=/root/.{{ item }} regexp="miniconda2" line="PATH=/opt/miniconda2/bin:$PATH"
  with_items:
      - bashrc
      - bash_profile

  # - name: Setup miniconda path
  #   shell: grep -q miniconda2 ~/.bashrc || echo 'PATH=/opt/miniconda2/bin:$PATH' >> ~/.bashrc
  # lineinfile: dest=/etc/sysconfig/i18n regexp="LC_CTYPE" line='LC_CTYPE="en_US.UTF-8"'

  # - name: Upgrade conda
  # conda: name=conda state=latest executable=/opt/miniconda2/bin/conda

- name: Make sure pillow installed
  conda: name=pillow state=latest executable=/opt/miniconda2/bin/conda

- name: Checkout eclaim source code
  git: repo={{ deployment_url }} dest=/opt/eclaim_revamp force=yes  

- name: Setup pip requirements
  pip: requirements=/opt/eclaim_revamp/{{ item }}.txt virtualenv=/opt/miniconda2
  with_items:
     - requirements
     - req_test 
