---

- name: Install OS Dependencies
  yum: name={{ item }} state=present
  with_items:
    - git
    - unzip
    - tar
    - bzip2
    - epel-release
    - gcc
    - glibc-common

- name: Install App Dependencies
  yum: name={{ item }} state=present
  with_items:
    - postgresql-devel
    - nginx
    - logrotate

- name: Create nginx requisite directories
  file: path=/etc/nginx/{{ item }} state=directory
  with_items:
    - sites-available
    - sites-enabled

- name: Install nginx template
  template: src=templates/eclaim_nginx.conf dest=/etc/nginx/sites-available/eclaim_nginx.conf mode=0644

- name: Symlink to enable site
  file: src=/etc/nginx/sites-available/eclaim_nginx.conf dest=/etc/nginx/sites-enabled/eclaim_nginx.conf state=link

- name: Enabled sites-enabled / sites-available from nginx.conf
  lineinfile: dest=/etc/nginx/nginx.conf
              line='include /etc/nginx/sites-enabled/*;'
              insertafter=EOF
              state=present

- name: Rub out old eclaim_revamp folder
  file: path=/opt/eclaim_revamp state=absent

- include: install_conda.yml

- name: Setup miniconda path
  lineinfile: dest=/root/.bashrc regexp="miniconda2" line="PATH=/opt/miniconda2/bin:$PATH"

  # - name: Setup miniconda path
  #   shell: grep -q miniconda2 ~/.bashrc || echo 'PATH=/opt/miniconda2/bin:$PATH' >> ~/.bashrc
  # lineinfile: dest=/etc/sysconfig/i18n regexp="LC_CTYPE" line='LC_CTYPE="en_US.UTF-8"'

  # - name: Upgrade conda
  # conda: name=conda state=latest executable=/opt/miniconda2/bin/conda

- name: Make sure pillow installed
  # conda: name=pillow state=latest executable=/opt/miniconda2/bin/conda
  shell: /opt/miniconda2/bin/conda list | grep -q -i pillow || /opt/miniconda2/bin/conda install --yes -c conda-forge pillow
  args:
    creates: /opt/miniconda2/lib/python2.7/site-packages/PIL 

- name: Checkout eclaim source code
  git: repo={{ deployment_url }} dest=/opt/eclaim_revamp force=yes version=master

- name: Setup pip requirements
  pip: requirements=/opt/eclaim_revamp/{{ item }}.txt virtualenv=/opt/miniconda2
  with_items:
     - requirements
     - req_test 
  # - name: Setup pip requirements
  # pip: requirements=/opt/eclaim_revamp/req_test.txt
  #

- name: Setup miniconda path
  #   shell: grep -q miniconda2 ~/.bashrc || echo 'PATH=/opt/miniconda2/bin:$PATH' >> ~/.bashrc
  lineinfile: dest=/root/.bashrc regexp="miniconda2" line="PATH=/opt/miniconda2/bin:$PATH"

  # - name: Setup miniconda path
  #   shell: grep -q miniconda2 ~/.bashrc || echo 'PATH=/opt/miniconda2/bin:$PATH' >> ~/.bashrc
  # lineinfile: dest=/etc/sysconfig/i18n regexp="LC_CTYPE" line='LC_CTYPE="en_US.UTF-8"'

  # - name: Upgrade conda
  # conda: name=conda state=latest executable=/opt/miniconda2/bin/conda

  # - name: Make sure pillow installed
  # conda: name=pillow state=latest executable=/opt/miniconda2/bin/conda
  # shell: /opt/miniconda2/bin/conda list | grep -q -i pillow || /opt/miniconda2/bin/conda install --yes -c conda-forge pillow
  # args:
          # creates: /opt/miniconda2/bin/pillow

  # - name: Git checkout sources
  # git: repo=https://lowkster:{{ deployment_password }}@bitbucket.org/eclaim_revamp_team/eclaim_revamp.git dest=/opt/eclaim_revamp accept_hostkey=yes force=yes

  # - name: Rename eclaim folder
  # shell: mv /opt/eclaim_revamp_team* /opt/eclaim_revamp

  # - name: Checkout eclaim source code
  # git: repo={{ deployment_url }} dest=/opt/eclaim_revamp force=yes  

- name: Setup pip requirements
  pip: requirements=/opt/eclaim_revamp/{{ item }}.txt virtualenv=/opt/miniconda2
  with_items:
     - requirements
     - req_test 
  # - name: Setup pip requirements
  # pip: requirements=/opt/eclaim_revamp/req_test.txt
  #
- include: django.yml
