---

- name: Install OS Dependencies (Redhat)
  package: name={{ item }} state=present
  with_items:
    - epel-release
    - gcc
    - glibc-common

- name: Install environment to avoid problems with environment
  template: src=templates/environment dest=/etc/environment

- name: Install uwsgi init file
  template: src=templates/uwsgi dest=/etc/rc.d/init.d/uwsgi mode=0755
  notify: start uwsgi

- name: Setup miniconda path
  lineinfile: dest=/root/.{{ item }} regexp="miniconda2" line="PATH=/opt/miniconda2/bin:$PATH"
  with_items:
    - bashrc
    - bash_profile

