---
- hosts: all
  roles:
    - { role: db_server, tags: db_server }
    - { role: app_server, tags: app_server }
    - { role: genzouw.postfix, tags: postfix }
    - { role: common, tags: common }

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

    - name: start uwsgi
      service: name=uwsgi state=started

    - name: start nginx
      service: name=nginx state=started
