---
- hosts: dbserver
  roles:
    - {role: db_server}

- hosts: appserver
  roles:
    - {role: app_server}
  # - include: app_server.yml
  # when: "'appserver' in group_names"
  # roles:
  #   - { role: db_server, tags: db_server }
  #   - { role: common, tags: common }

  
