---
# Defines tasks to install and configure Postfix

- name: Include the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - common
    - postfix

- name: Install packages for RedHat derivatives
  yum: name={{ item }} state=present 
  with_items: postfix_packages
  when: ansible_os_family == 'RedHat'
  tags:
    - common
    - postfix

# - name: Write SMTP authentication template
  # template: >
    # src=sasl_passwd.j2
    # dest={{ postfix_config_dir }}/sasl_passwd
    # mode=0600 owner=root group=root
  # notify:
    # - postmap sasl
  # when: postfix_use_smtp and postfix_relayhost_user and postfix_relayhost_pass
  # tags:
    # - common
    # - postfix

- name: Write Postfix configuration template
  template:
    src: "{{ item }}.j2"
    dest: "{{ postfix_config_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
    - header_checks
    - body_checks
    - main.cf
  tags:
    - common
    - postfix


- name: Write Dovecot configuration template
  template:
    src: "{{ item }}.j2"
    dest: "{{ dovecot_config_dir }}/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10-auth.conf
    - 10-mail.conf
    - 10-master.conf
    - 20-pop3.conf

- name: Start Postfix on server boot
  service: >
    name={{ item }}
    state=restarted
    enabled=yes
  with_items:
    - "{{ postfix_service }}"
    - dovecot
    - saslauthd
  tags:
    - common
    - postfix

