---

- name: Install Database Prerequisites (Debian)
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - sudo
    - postgresql
    - postgresql-contrib
    - libpq-dev

- name: Add root as temporary sudoers
  lineinfile: "dest=/etc/sudoers regexp='^root' line='root ALL=(ALL)       NOPASSWD: ALL' state=present"

- name: Ensure postgresql service is started
  service: name=postgresql state=started

- name: Install pg_hba.conf
  copy: src=files/pg_hba.conf dest=/etc/postgresql/9.5/main/pg_hba.conf
  notify: restart postgresql

- name: Find and register postgresql.conf file
  find: paths="/etc" patterns="post*.conf" recurse=True
  register: postgresql_conf_path

- name: Configure postgresql.conf
  template: src=templates/postgresql_debian.conf dest="{{ item.path }}" force=yes
  notify: restart postgresql
  with_items: postgresql_conf_path.files

- name: Restart postgresql
  service: name=postgresql state=restarted
